### ISSUE TITLE
Resovle как callback 

### ISSUE THREAD

**Issue by mitisit89** [StreetXHasu/XMLparserToOpenCart#1]
https://github.com/StreetXHasu/XMLparserToOpenCart/blob/81287cbc6ea6bb4a860e396a47da3d8c9699b69b/index.js#L123

return new Proimise((resolve)=>setTimeout(()=>resolve(),ms))
Working

**Comment by StreetXHasu** [comment]
В смысле, нет никакой разницы и так и так работает

**Comment by mitisit89** [comment]
Разница есть. В моем варианте resovle callbackFn,а в твоем это параметр
